import os
import json
import logging
from datetime import datetime
from urllib import request, error
from base64 import b64encode

from sqlalchemy.orm import Session
from sqlalchemy import create_engine, Column, Integer, String, Text, DateTime, JSON
from sqlalchemy.orm import DeclarativeBase

logger = logging.getLogger(__name__)

DATABASE_URL   = os.getenv("DATABASE_URL", "postgresql://siem:siempass@localhost:5432/siemdb")


JIRA_URL       = os.getenv("JIRA_URL", "")          # e.g. https://myorg.atlassian.net
JIRA_USER      = os.getenv("JIRA_USER", "")
JIRA_TOKEN     = os.getenv("JIRA_API_TOKEN", "")
JIRA_PROJECT   = os.getenv("JIRA_PROJECT_KEY", "SEC")

GITHUB_TOKEN   = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO    = os.getenv("GITHUB_REPO", "")        # e.g. myorg/siem-incidents



class Base(DeclarativeBase):
    pass


class Incident(Base):
    __tablename__ = "incidents"
    id          = Column(Integer, primary_key=True)
    created_at  = Column(DateTime, default=datetime.utcnow)
    alert_id    = Column(Integer)
    title       = Column(String(300))
    description = Column(Text)
    severity    = Column(String(20))
    source_ip   = Column(String(45))
    status      = Column(String(50), default="open")
    assignee    = Column(String(100), nullable=True)
    external_id = Column(String(200), nullable=True)   # Jira key / GitHub issue #
    metadata_   = Column(JSON, default=dict)


def _ensure_table():
    engine = create_engine(DATABASE_URL)
    Base.metadata.create_all(engine)
    return engine


def _create_local_ticket(engine, alert: dict) -> dict:
    with Session(engine) as session:
        incident = Incident(
            alert_id    = alert.get("alert_id", 0),
            title       = f"[{alert.get('severity','?').upper()}] {alert.get('rule_name','Alert')}",
            description = _build_description(alert),
            severity    = alert.get("severity", "medium"),
            source_ip   = alert.get("source_ip", "N/A"),
            metadata_   = {
                "rule_id":   alert.get("rule_id"),
                "event":     alert.get("event", {}),
                "created_by": "siem-playbook",
            },
        )
        session.add(incident)
        session.commit()
        return {"id": incident.id, "title": incident.title}


def _build_description(alert: dict) -> str:
    event = alert.get("event", {})
    lines = [
        f"## SIEM Alert: {alert.get('rule_name')}",
        f"",
        f"**Severity:** {alert.get('severity','?').upper()}",
        f"**Source IP:** {alert.get('source_ip','N/A')}",
        f"**Rule ID:** {alert.get('rule_id','N/A')}",
        f"**Time:** {datetime.utcnow().isoformat()}",
        f"",
        f"### Event Details",
        f"- Category: {event.get('category','N/A')}",
        f"- Event Type: {event.get('event_type','N/A')}",
        f"- Username: {event.get('username','N/A')}",
        f"- Message: {event.get('message','N/A')}",
        f"",
        f"### Raw Log",
        f"```",
        event.get("raw_log", "N/A"),
        f"```",
        f"",
        f"*Auto-generated by SIEM Lite playbook runner*",
    ]
    return "\n".join(lines)


def _create_jira_ticket(alert: dict) -> tuple[bool, str]:
    if not all([JIRA_URL, JIRA_USER, JIRA_TOKEN]):
        return False, "Jira not configured"
    try:
        severity_priority = {
            "low": "Low", "medium": "Medium",
            "high": "High", "critical": "Highest"
        }
        payload = {
            "fields": {
                "project":     {"key": JIRA_PROJECT},
                "summary":     f"[SIEM] {alert.get('rule_name')} — {alert.get('source_ip')}",
                "description": _build_description(alert),
                "issuetype":   {"name": "Bug"},
                "priority":    {"name": severity_priority.get(alert.get("severity", "medium"), "Medium")},
                "labels":      ["siem", "security", "auto-generated"],
            }
        }
        creds = b64encode(f"{JIRA_USER}:{JIRA_TOKEN}".encode()).decode()
        req = request.Request(
            f"{JIRA_URL}/rest/api/3/issue",
            data=json.dumps(payload).encode(),
            headers={
                "Authorization": f"Basic {creds}",
                "Content-Type": "application/json",
            },
        )
        with request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            return True, data.get("key", "unknown")
    except Exception as e:
        return False, str(e)


def _create_github_issue(alert: dict) -> tuple[bool, str]:
    if not all([GITHUB_TOKEN, GITHUB_REPO]):
        return False, "GitHub not configured"
    try:
        severity = alert.get("severity", "medium")
        payload  = {
            "title":  f"[SIEM-{severity.upper()}] {alert.get('rule_name')} — {alert.get('source_ip')}",
            "body":   _build_description(alert),
            "labels": ["security", f"severity:{severity}", "siem"],
        }
        req = request.Request(
            f"https://api.github.com/repos/{GITHUB_REPO}/issues",
            data=json.dumps(payload).encode(),
            headers={
                "Authorization": f"token {GITHUB_TOKEN}",
                "Content-Type":  "application/json",
                "Accept":        "application/vnd.github.v3+json",
            },
        )
        with request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            return True, f"#{data.get('number')} — {data.get('html_url')}"
    except Exception as e:
        return False, str(e)


def execute(alert_payload: dict) -> dict:

    results   = {}
    engine    = _ensure_table()
    ext_id    = None


    local = _create_local_ticket(engine, alert_payload)
    results["local"] = {"status": "success", "ticket_id": local["id"], "title": local["title"]}
    logger.info(f"📋 Local incident #{local['id']} created: {local['title']}")


    jira_ok, jira_ref = _create_jira_ticket(alert_payload)
    results["jira"]   = {"status": "success" if jira_ok else "skipped", "ref": jira_ref}
    if jira_ok:
        ext_id = jira_ref
        logger.info(f"Jira ticket created: {jira_ref}")


    gh_ok, gh_ref   = _create_github_issue(alert_payload)
    results["github"] = {"status": "success" if gh_ok else "skipped", "ref": gh_ref}
    if gh_ok and not ext_id:
        ext_id = gh_ref
        logger.info(f"GitHub issue created: {gh_ref}")


    if ext_id:
        with Session(engine) as session:
            inc = session.query(Incident).filter(Incident.id == local["id"]).first()
            if inc:
                inc.external_id = ext_id
                session.commit()

    return {
        "status":     "success",
        "local_id":   local["id"],
        "external_id": ext_id,
        "channels":   results,
    }
